VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

ENCODER_MAP_ENABLE = yes

TAP_DANCE_ENABLE = yes
QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes

OLED_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes
