VIA_ENABLE = yes
VIAL_ENABLE = yes
# VIAL_ENCODERS_ENABLE = yes
VIAL_INSECURE = yes

TAP_DANCE_ENABLE = yes
QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = no
# DYNAMIC_MACRO_ENABLE = no
# SWAP_HANDS_ENABLE = yes

AUDIO_ENABLE = no
MUSIC_ENABLE = no
